name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: Sisältää skipin
        run: echo "sisältää skipin ${{ contains(join(github.event.commits.*.message, ' '), '#skip') }}"
        if: ${{ contains(join(github.event.commits.*.message, ' '), '#skip') }}
      - name: ei sisällä skippiä
        run: echo "ei sisällä skippiä ${{ contains(join(github.event.commits.*.message, ' '), '#skip') }}"
        if: ${{ !contains(join(github.event.commits.*.message, ' '), '#skip') }}

